name: helpalife_mobile
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.5.1+1
  loading_animation_widget: ^1.3.0
  get: ^4.7.2
  intl: ^0.20.2
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/helpalife_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
   - images/


